main:

- name: Home
  url: /
  weight: 1

- name: Publications
  url: /publications/
  weight: 2

- name: Curriculum Vitae
  url: /files/cv.pdf
  weight: 3

social:
- name: email
  url: mailto:phuongnt@unist.ac.kr
  weight: 1
  params:
    icon: fas fa-envelope

- name: LinkedIn
  url: https://www.linkedin.com/in/phuongnt197/
  weight: 2
  params:
    icon: fab fa-linkedin

- name: GitHub
  url: https://github.com/phuongnt197
  weight: 3
  params:
    icon: fab fa-github